name: flask workflow
on: push

jobs:
  my-job:
    name: flask-workflow
    runs-on: flask
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3 
    - name: dependency
      run: |
        pip3 install -r requirements.txt;
    - name: Run server 
      run: |
        python3 server.py > log.txt 2>&1 &    