name: flask workflow
on: push

jobs:
  my-job:
    name: flask-workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3 
    - name: pip upgrade
      run: |
        python -m pip install --upgrade pip  
    - name: dependency
      run: |
        pip3 install -r requirements.txt;
    - name: Run server 
      run: |
        python3 run.py > log.txt 2>&1 &    
